### ISSUE TITLE
Support for "secrets" in 

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#1388] opened 2021-04-09 04:26 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jLopezbarb** [comment] 2021-05-05 11:42
Possible duplicate of [this](https://github.com/okteto/okteto/issues/1389)

**Closed** 2021-05-05 11:50 UTC
