### ISSUE TITLE
Request: Implement networks or network_mode

### ISSUE THREAD

**Issue by ufukbakan** [okteto/okteto#2935] opened 2022-07-17 19:51 UTC
I can not deploy a server-client application where server and client are seperate node.js containers. I use docker compose.
Also Im not sure is container_name field working correctly or not.
```bash
2022-07-17 19:48:51.68 UTCwolf-sheep-rabbit-client-56599ccf4c-vdrrswolf-sheep-rabbit-client7:48:51 PM [vite] http proxy error:
2022-07-17 19:48:51.68 UTCwolf-sheep-rabbit-client-56599ccf4c-vdrrswolf-sheep-rabbit-clientError: getaddrinfo ENOTFOUND wolf-sheep-rabbit-server
2022-07-17 19:48:51.68 UTCwolf-sheep-rabbit-client-56599ccf4c-vdrrswolf-sheep-rabbit-client at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```

**Comment by jLopezbarb** [comment] 2022-08-22 13:37
Hi @ufukbakan, We didn't detect any problem connecting from different services on compose. We've tried with https://github.com/okteto/movies-with-compose without any issue. Can you provide the docker compose you are trying to deploy (removing sensitive information) so we can try to reproduce the issue?

**Comment by jLopezbarb** [comment] 2022-09-05 12:25
Hi @ufukbakan, I'm closing the issue since we aren't able to reproduce the issue. Please, feel free to reopen it adding more information to be able to reproduce the issue

**Closed by jLopezbarb** 2022-09-05 12:25 UTC
Labels: question, ready
