### ISSUE TITLE
Can't delete context displayed by 'okteto context show'

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2984] opened 2022-08-04 06:02 UTC
**Describe the bug**
Running `okteto context show` shows the the following:
```
❯ okteto context list
Name                       Namespace    Builder                                Registry
https://cloud.okteto.com   rberrelleza  tcp://buildkit.cloud.okteto.net:1234   registry.cloud.okteto.net
https://demo.okteto.dev *  rberrelleza  tcp://buildkit.demo.okteto.dev:1234    registry.demo.okteto.dev
https://ramiro.okteto.dev  movies       tcp://buildkit.ramiro.okteto.dev:1234  registry.ramiro.okteto.dev
civo                       default      docker                                 -
okteto-dev                 okteto       docker                                 -
okteto-prod                default      docker                                 -
okteto-staging             okteto       docker                                 -
ramiro-dev                 okteto       docker                                 -
```
When I want to delete `ramiro-dev`, it fails like this:

```
 okteto context delete ramiro-dev
 x  'https://ramiro-dev' context doesn't exist. Valid options are: [https://ramiro.okteto.dev, https://cloud.okteto.com, https://demo.okteto.dev]
```

I assume that it fails because it's a kubernetes context instead of an okteto context. If that's the case, we should have a clear error message instead of saying that it doesn't exist. 

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.5.2

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

**Comment by rberrelleza** [comment] 2022-08-04 06:03
I think that `okteto context show` should also identify okteto contexts vs kubernetes context more clearly

**Comment by jLopezbarb** [comment] 2022-08-04 09:55
It fails because it's a k8s context and not an okteto cluster. 

I think that we can make two things to improve UX:
1. Return a clearer error saying that you can only remove an okteto cluster if we detect that the context is a k8s one.
2. Adding a new column on the `okteto ctx ls` command to show if the cluster is managed by okteto or not.

In earlier versions when selecting contexts we were splitting the ones from k8s from the ones managed by okteto but we discarded the idea because it could be confusing for the users.

**Comment by RinkiyaKeDad** [comment] 2022-09-02 08:43
Duplicate of: https://github.com/okteto/okteto/issues/2957

**Comment by pchico83** [comment] 2022-10-04 06:02
Duplicated of https://github.com/okteto/okteto/issues/2957

**Closed by pchico83** 2022-10-04 06:02 UTC
Labels: medium, epsilon
