### ISSUE TITLE
My `okteto up` sometimes fails with "failed to prepare subPath for volumeMount` error

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#2214] opened 2022-01-31 08:30 UTC
**Describe the bug**
Issue looks temporal, it isusally works when I run `okteto up` again.

**Describe the solution you would like**
 
Ignore/retry these errors for 2 minutes

**Comment by pchico83** [comment] 2022-07-17 10:32
@jLopezbarb I found a way to repro this, maybe there are other reasons too.
If the init container fills the volume with the original content of the image, `okteto up` fails with this error

**Comment by jLopezbarb** [comment] 2022-09-30 09:37
Do you remember the manifest that you were using? I think we fixed one related with having it from a compose but not sure if it's the same error

**Comment by pchico83** [comment] 2022-09-30 10:04
@jLopezbarb you can create a docker image with a 2Gi file in `/src`. Then run `okteto up` with something like this:
```
sync:
   - .:/src
persistentVolume:
   size: 1Gi
``` 

The init container will initialize `/src`, the volume runs out of space, and you should get this error.

**Comment by jLopezbarb** [comment] 2022-10-20 10:26
I could reproduce the issue, but since it's something that can be a pain, I will propose three different solutions:

1. Can/Should we create a new init container that checks if the volume is full or not after the cp? We can't asume that all the user images have the necessary utilities to check if the disk is full. I would only need `cp`, `df` and `awk`/`grep` but I don't know if I can asume that the user will have those utilities in their dev images. 

I will add pseudocode for the first solution that wouldn't have to create any new init container:
``` bash
if testIfVolumeIsInitializated(volume) {
    print(volume initialized. Skipping);
} else {
    execCopyCommand(volume)
}
# We have to check if there is space left because we can do okteto up
# get the proper error and if we do okteto up again it will fail with the error that we get now
if !isSpaceLeft(volume) { 
    exit 1
}
exit 0
```

2. Another solution could be leaving the init-container volume as it is and check it  in another inti container that has an image with the proper shell utilities or an image with a simple script in whatever language that checks if the volume mount has space left.

3. I don't know which consequences this can have, but we could run the `init-volume-container` before `okteto-bin` and add the volume mounts to `okteto-bin`. Since we have the control of `okteto-bin` we can add the check for volume spaces as part of the binary.

I think the best options are 1 and 2, if we asume that `awk` and `df` are going to be always in the container 1 would be the best one, but if we can't asume that I think 2 is the safest solution. Number 3 can have some more implications and I would avoid doing that

**Comment by pchico83** [comment] 2022-10-20 10:32
@jLopezbarb is it possible to check it based on the logs of `init-volume-container`?

**Comment by jLopezbarb** [comment] 2022-10-20 10:35
It's possible if we run the copy command. But we are skipping the copy command if the `init-volume-container` is initialised, so we will have the same error if we run two times `okteto up`. The first one is going to initialise the volume and the second one will skip validation and will throw `failed to prepare subPath for volumeMount` error

**Comment by pchico83** [comment] 2022-10-20 10:38
@jLopezbarb What about catching the error `failed to prepare subPath for volumeMount` and show an error telling the volume is full and a CTA to increase the volume size?

**Comment by jLopezbarb** [comment] 2022-10-20 10:42
> @jLopezbarb What about catching the error `failed to prepare subPath for volumeMount` and show an error telling the volume is full and a CTA to increase the volume size?

I would try to avoid that since `failed to prepare subPath for volumeMount` can also happen if the user set the wrong mount path in their app and run `okteto up` believing that their application is correct and we will tell the user to increase the volume size but that won't fix the original issue...

**Comment by pchico83** [comment] 2022-10-20 10:44
> > @jLopezbarb What about catching the error `failed to prepare subPath for volumeMount` and show an error telling the volume is full and a CTA to increase the volume size?
> 
> I would try to avoid that since `failed to prepare subPath for volumeMount` can also happen if the user set the wrong mount path in their app and run `okteto up` believing that their application is correct and we will tell the user to increase the volume size but that won't fix the original issue...

@jLopezbarb are we already managing that error? do you have a sample where that happens?

**Closed** 2022-10-26 08:02 UTC
Labels: bug, keep, customer reported, ready, echoes/intent: fix
