### ISSUE TITLE
okteto.yml with autocreate set to true fails on okteto 2.x

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2585] opened 2022-04-22 20:11 UTC
**Describe the bug**
Doing okteto up on a manifest like this:
```
name: XXX 
image: LINK_TO_MY_DOCKER_IMAGE
imagePullPolicy: Always
namespace: YYY
workdir: /tmp
autocreate: true
initContainer:
  image: okteto/bin:1.3.4
command:
  - bash
forward:
  - 8080:8080
serviceAccount: mlp-spark 
```

Fails with this error:
```
Application 'XXX' not found in namespace 'YYY '
    Verify that your application is running and your okteto context is pointing to the right namespace
    Or set the 'autocreate' field in your okteto manifest if you want to create a standalone development container
    More information is available here: https://okteto.com/docs/reference/cli/#up
```

**To Reproduce**
The user reported that this worked fine on a previous version of Okteto CLI

okteto version: 2.1.0
vs code extension: v0.4.1
VS code version: 1.66.2

**Comment by rberrelleza** [comment] 2022-04-22 20:14
user mentioned that moving to the v2 format worked fine. 
```
dev:
  XXXX:
    autocreate: true
    namespace: YYYY
    initContainer:
     image: okteto/bin:1.3.4
    image: LINK_TO_MY_DOCKER_IMAGE
    command: bash
    workdir: /tmp
    sync:
      - .:/usr/src/app
    forward:
      - 8080:8080
    serviceAccount: mlp-spark
```


This might be an issue with how the extension manages the v1 vs v2

**Comment by rberrelleza** [comment] 2022-04-23 03:48
Upon further research, it looks like setting the `OKTETO_AUTODEPLOY` env var is what's triggering this issue. As soon as I unset that env var, it worked as expected.

**Comment by rachitchauhan43** [comment] 2022-04-23 21:47
Awesome, it works now with v0.4.3 of the extension.

**Comment by AgustinRamiroDiaz** [comment] 2022-05-03 11:09
It might be related to [this](https://github.com/okteto/okteto/issues/2609)

**Comment by jmacelroy** [comment] 2022-05-05 21:25
@rberrelleza was there an extension update that fixed this?

**Comment by rberrelleza** [comment] 2022-05-10 14:43
We removed the referred env var on the vscode extension. But I don't think we know the root cause of this yet.

**Comment by jLopezbarb** [comment] 2022-05-17 11:08
We changed the behaviour of the `OKTETO_AUTODEPLOY` env var and `deploy` flag on the `okteto up` command from set the autocreate field on the manifest to deploying what's under the deploy section. 
We didn't contemplate that it could break the vscode extension

**Comment by jLopezbarb** [comment] 2022-06-06 12:09
Closing this issue. [The root of the cause was found](https://github.com/okteto/okteto/issues/2585#issuecomment-1128734621). @rberrelleza if you think we should do anything else, feel free to reopen it again

**Closed by jLopezbarb** 2022-06-06 12:09 UTC
Labels: customer reported
