### ISSUE TITLE
Upgrade Buildkit [timeboxed 2 days]

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3548] opened 2023-04-12 16:32 UTC
From https://okteto.slack.com/archives/C02T9BKMS4V/p1681287455878799

## Context

We want to upgrade BuildKit to benefit from new features such as [multiple cache exports](https://github.com/moby/buildkit/pull/3024).

We have already implemented support for it but it will be disabled until this issue is delivered.

- Current version: `0.9.2`
- Min Target version: `0.11`

## Acceptance Criteria
- [ ] Buildkit upgraded to version min `0.11`
- [ ] ~Remove the limit of 1 export cache in the CLI~
- [ ] Testing multiple cache exports is done either manually or via integration tests (ideally)

**Comment by andreafalzetti** [comment] 2023-04-18 21:20
https://github.com/okteto/app/pull/6312

**Comment by viddo** [comment] 2023-04-21 09:11
☝️ Discussed in daily today - Since this upgrade is no longer a blocker for other issues/features atm we'll await next chart release cut (v1.8) ETA next sprint/week (~April 26-28) before merging. This will give it some time to soak on staging/cloud before pushing it out to Saas/self-hosted customers, and give us more time to identify potential regressions or bugs.

**Comment by jLopezbarb** [comment] 2023-04-26 11:17
Already merged

**Closed by jLopezbarb** 2023-04-26 11:17 UTC
Labels: echoes/intent: grow
