### ISSUE TITLE
okteto deploy should not fail if deploy section is empty

### ISSUE THREAD

**Issue by jLopezbarb** [okteto/okteto#3065] opened 2022-09-02 12:56 UTC
**Describe the bug**
Right now we are failing when an `okteto manifest v2` with an empty deploy section is deployed. We should be showing an information message linking [the deploy docs](https://www.okteto.com/docs/reference/manifest/#deploy-string-optional) and a message indicating that there is nothing to deploy

**To Reproduce**

1. Create the following okteto manifest:
```yaml
build:
  a:
    context: .
  b:
    context: .
  c:
    context: .
    dockerfile: a.Dockerfile
```
1. Run `okteto deploy`
1. See error
<img width="547" alt="Captura de pantalla 2022-09-02 a las 14 55 13" src="https://user-images.githubusercontent.com/25170843/188150378-f5a853bb-de63-475a-b08a-3e39cdfa1009.png">

**Expected behavior**
I don't want to fail, only a message indicating that the deploy section is empty and a link to the docs

**Desktop (please complete the following information):**

- Version 2.6.0

**Comment by jmacelroy** [comment] 2022-09-07 20:35
@jLopezbarb What would we be doing if we don't fail? I think in this case it's an error and a failure is expected. I think we could have a better message but I also don't know that linking to documentation is quite helpful either. It doesn't look great and docs can be a moving target.

What about simply updating the message to `The deploy command was provided but there is no deploy section defined in the manifest, <insert filename>.` Then I think either the user would know and add it or would visit docs and would be able to easily find the info they need. What do you think?

**Comment by pchico83** [comment] 2022-09-08 05:42
> @jLopezbarb What would we be doing if we don't fail? I think in this case it's an error and a failure is expected. I think we could have a better message but I also don't know that linking to documentation is quite helpful either. It doesn't look great and docs can be a moving target.
> 
> What about simply updating the message to `The deploy command was provided but there is no deploy section defined in the manifest, <insert filename>.` Then I think either the user would know and add it or would visit docs and would be able to easily find the info they need. What do you think?

@jmacelroy  there are valid uses cases for manifests without `deploy` section. For example, a manifest that only has `dependencies`, or I have also seen repos with just `build` and `dev` sections. If the `deploy` section is not defined, we should show an info message saying that there is nothing to deploy. But it's not even a warning, it's a valid use case

**Comment by rberrelleza** [comment] 2022-10-11 01:58
@pchico83  Could you explain more of the use case of having dependencies but no local deploy?  Maybe we should only hide the error message if deploy is empty AND there are dependencies? (because in this scenario, you do have something to deploy). 

For the other scenario you mention (dev and or build defined but not deploy), I think that if the user doesn't define a deploy section, and they are calling 'okteto deploy', then the call should fail with the message that @jmacelroy recommended, since there is no way to complete the desired action.

**Comment by pchico83** [comment] 2022-10-11 07:34
@rberrelleza for dependencies, it's super common to have a meta repo with just `dependencies`. This is a way to orchestrate the deployment of several repos in single command.
For the scenario of `dev` and `build` defined but not `deploy`, the problem is that the installer job runs `okteto deploy`.  That means for these cases users cannot deploy a repo from the UI or with `okteto pipeline deploy`. And it's very handy for example to build your images on remote before running `okteto up`.
What are the reasons behind forcing a strict behavior? Showing an info message seems much more flexible

**Comment by rberrelleza** [comment] 2022-10-13 21:49
> What are the reasons behind forcing a strict behavior? Showing an info message seems much more flexible

I think showing the wrong message is misleading and makes it more complicated for the user to find the right help. I get confused when I see that message. My first feeling is always that I somehow picked the wrong file or something.

**Comment by rberrelleza** [comment] 2022-10-13 21:50
> For the scenario of dev and build defined but not deploy, the problem is that the installer job runs okteto deploy.

To me that's an internal implementation. I think we should focus on polishing the user experience first, and then the automated one.

**Comment by pchico83** [comment] 2022-11-05 11:08
Let's close this one for now

**Closed by pchico83** 2022-11-05 11:08 UTC
Labels: ready

**Comment by jLopezbarb** [comment] 2022-12-14 11:38
> @pchico83, are there any way to deploy dependencies only?
> I ran into the same as @jLopezbarb - I need to deploy different dependencies and don't need to deploy anything from the project in which deploy triggered.

@serhiikovalenkoextcheckrcom Not right now, I think that could be another issue. We should be creating a command to deploy/destroy specific dependencies so I can redeploy one of them without having to go to the UI and click on redeploy
