### ISSUE TITLE
If the current context is deleted from config.json, when I execute any command I get a stack trace

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2773] opened 2022-06-09 15:45 UTC
**Describe the bug**
If I go to `context/config.json` and I delete the current context from the list of contexts (without deleting the `current-context` property`), I get the following stack trace every time I execute a command

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x23074a1]

goroutine 1 [running]:
github.com/okteto/okteto/cmd/utils.OktetoSelector.getInitialPosition({{0x317a873, 0x6f}, {0xc001bf1000, 0x19, 0x2e}, 0x19, 0xc001616d20, 0x0, 0x0}, {0x360aa38, ...})
	github.com/okteto/okteto/cmd/utils/selector.go:381 +0xa1
github.com/okteto/okteto/cmd/utils.(*OktetoSelector).Run(0xc00098cff0, {0x360aa38, 0xc000194000})
	github.com/okteto/okteto/cmd/utils/selector.go:116 +0xdd
github.com/okteto/okteto/cmd/utils.AskForOptionsOkteto({0x360aa38, 0xc000194000}, {0xc001bf1000, 0x19, 0x2e}, {0x317a873, 0x6f}, {0x2fdf6d5, 0x0})
	github.com/okteto/okteto/cmd/utils/selector.go:96 +0x2fc
github.com/okteto/okteto/cmd/context.getContext({0x360aa38, 0xc000194000}, 0xc00201fc30)
	github.com/okteto/okteto/cmd/context/use.go:127 +0x65
github.com/okteto/okteto/cmd/context.(*ContextCommand).Run(0x0, {0x360aa38, 0xc000194000}, 0xc00201fc30)
	github.com/okteto/okteto/cmd/context/use.go:102 +0x13f
github.com/okteto/okteto/cmd/namespace.List.func1(0xc00017cc80, {0x4d3c1d8, 0x0, 0x0})
	github.com/okteto/okteto/cmd/namespace/list.go:37 +0xfc
github.com/spf13/cobra.(*Command).execute(0xc00017cc80, {0x4d3c1d8, 0x0, 0x0})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000135400)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	github.com/okteto/okteto/main.go:136 +0x9a9
```

**To Reproduce**

1. Go to '.~/.okteto/context/config.json'
2. Check the `current-context` property and delete that context from the list `contexts` (without deleting `current-context`)
3. Execute any command and you would get the error

**Expected behavior**
I would see 2 options:
* An error indicating that the current context doesn't exist and some hint about how to proceed
* A warning indicating that the current context was corrupted or missconfigured and ask the user again to configure it

**Desktop (please complete the following information):**

- CLI version: I tested it using `2.3.3` and the build from `master`

**Additional context**
N/A

**Comment by AdrianPedriza** [comment] 2022-09-16 10:33
I cannot reproduce it with the current CLI version. Closing this issue.

**Closed** 2022-09-16 10:33 UTC
Labels: bug, high, epsilon
