### ISSUE TITLE
Okteto cli selection prompt does not work with Git Bash or cygwin terminals on Windows

### ISSUE THREAD

**Issue by danielbodis** [okteto/okteto#2774] opened 2022-06-09 17:19 UTC
In Git Bash terminal run the following command: okteto context use (or any other command which has a selection prompt).
The okteto cli will display the selection text, then quit right away with an "Invalid option" message.

**Desktop (please complete the following information):**

- OS: Windows
- Terminal: Git Bash (mintty 3.5.2) or cygwin (mintty 3.5.2)

**Comment by jLopezbarb** [comment] 2022-08-19 09:47
Hi @danielbodis, I was unable to reproduce the issue. 
I was able to move through the selector without any problems. Can you check your version of cygwin to try to use the same version?
<img width="443" alt="Captura de pantalla 2022-08-19 114151" src="https://user-images.githubusercontent.com/25170843/185591929-c993e3f8-635f-4315-bb10-66de58b84baa.png">

**Comment by jLopezbarb** [comment] 2022-08-26 09:56
Closing this since we are unable to reproduce. @danielbodis If you are still facing the issue don't hesitate to re-open it and provide the Cygwin version

**Closed by jLopezbarb** 2022-08-26 09:56 UTC
Labels: bug, high, customer reported, ready
