### ISSUE TITLE
`okteto up` fails on a repo with a docker-compose, if run after okteto deploy

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2598] opened 2022-04-26 23:53 UTC
**Describe the bug**
`okteto up` fails on a repo with a docker-compose. this is the error I got:
```
okteto up
 i  Using rberrelleza @ demo.okteto.dev as context
 !  okteto manifest has no 'dev' section.
 ?  Do you want to configure okteto manifest now? [y/n]y
 ✓  Okteto manifest (okteto.yml) deploy and build configured successfully
 ✓  Development container 'workshop' configured successfully
 ✓  Okteto manifest (okteto.yml) configured successfully
 i  '.stignore' doesn't exist in folder '/Users/ramiro/okteto/workshop-dashboard'.
 i  Okteto requires a '.stignore' file to ignore file patterns that help optimize the synchronization service.
 ?  Do you want to infer defaults for the '.stignore' file? (otherwise, it will be left blank) [y/n] y 
 i  Development environment 'workshop-dashboard' already deployed.
 i  To redeploy your development environment run 'okteto deploy' or 'okteto up workshop --deploy'
 x  Couldn't activate your development container
    Deployment.apps "workshop-okteto" is invalid: spec.template.spec.containers[0].volumeMounts.subPath: Invalid value: "/Users/ramiro/okteto/workshop-dashboard": must be a relative path
    Find additional logs at: /Users/ramiro/.okteto/rberrelleza/workshop/okteto.log
```

**To Reproduce**

1. clone a repo with a docker-compose.yaml file
2. run `okteto deploy`
3. run `okteto up`
4. walk through the 'okteto.yml' generation code
6. See error

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.1.0

**Additional context**
[okteto.log](https://github.com/okteto/okteto/files/8567555/okteto.log)

**Comment by AdrianPedriza** [comment] 2022-05-13 15:24
@rberrelleza I could't reproduce your error. Can you try with https://github.com/okteto/microservices-demo-compose ?

**Comment by jLopezbarb** [comment] 2022-07-15 11:25
@rberrelleza @AdrianPedriza Any update on this? If it's not reproducible anymore we can close it and reopen it when we have clear reproduction steps

**Comment by AdrianPedriza** [comment] 2022-07-15 13:50
> @rberrelleza @AdrianPedriza Any update on this? If it's not reproducible anymore we can close it and reopen it when we have clear reproduction steps

I couldn't reproduce it using https://github.com/okteto/microservices-demo-compose

**Closed** 2022-07-19 14:37 UTC
Labels: high
