### ISSUE TITLE
Support for "env_file" in okteto stacks

### ISSUE THREAD

**Issue by pchico83** [okteto/okteto#826] opened 2020-04-19 05:10 UTC
**Is your feature request related to a problem? Please describe.**
I want to run `okteto stack deploy` with a bunch of environment variables.

**Describe the solution you'd like**
Support for `env_file`:
https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

**Comment by ZaxR** [comment] 2020-05-17 06:22
Dupe of #793 ? I would very much like this feature as well

**Comment by pchico83** [comment] 2020-05-18 08:11
@ZaxR thanks for the interest. This will be implemented very soon :-)

**Closed** 2020-10-06 07:51 UTC
Labels: stack
