### ISSUE TITLE
Spinner for `okteto deploy` says `Destroying your development environment`

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3668] opened 2023-05-26 12:41 UTC
**Describe the bug**
When I'm deploying an application for example, running `okteto deploy --remote` the spinner that is displayed says `Destroying your development environment`

<img width="1509" alt="Captura de pantalla 2023-05-26 a las 14 38 58" src="https://github.com/okteto/okteto/assets/3510171/e2f1ba47-b3b5-4816-919b-792fbcbcc141">

**To Reproduce**

1. Create a manifest with some sleep command on the `deploy` section and execute `okteto deploy --remote` using that manifest
2. Check the spinner displayed in the UI

**Expected behavior**

The spinner should say `Deploying your development environment` as it was in `2.15`

**Desktop (please complete the following information):**

- Version: `2.16.0`

**Additional context**

In `2.15.0` the spinner was correct

**Comment by NitishKumar06** [comment] 2023-05-26 12:50
This issue is a duplicate of https://github.com/okteto/okteto/issues/3572. 

We're currently working on this change and it'll be resolved soon. (Due to exams, i couldn't keep up with the time for solving this issue). The fix will be applied shortly!

**Comment by NitishKumar06** [comment] 2023-05-28 09:03
[This](https://github.com/okteto/okteto/pull/3584) PR solves fixes this issue.

**Comment by NitishKumar06** [comment] 2023-05-29 16:43
**Update:** The PR is finally merged. Hence we're ready to close this issue.

**Closed** 2023-05-30 05:22 UTC
Labels: bug, echoes/intent: fix
