### ISSUE TITLE
[Feature Request] Add specific labels on the creation of an issue

### ISSUE THREAD

**Issue by nitishfy** [okteto/okteto#3506] opened 2023-03-30 15:52 UTC
**Is your feature request related to a problem? Please describe.**
Having been contributing to Kubernetes, one of the best things that I found there is K8s-Robot which was automated by GitHub Actions. Every time someone opens up a new issue, the issue was automatically assigned a label of `needs-triage` rather than doing this manually. Whenever a reviewer/member finds an issue that needs to be worked upon, the comment under the issue `triage/accepted`  would add a new label `triage-accpeted` indicating that this issue is ready to be worked upon. Most of the time, maintainers have to go through the issue to look if there is someone who would like to work for - If yes, the maintainer assigns that issue. However, this task can be automated and can be documented under contributing guidelines like _Please refrain from assigning yourself an issue that has already been assigned to someone else_.

**Describe the solution you'd like**
- Implement similar actions for Okteto such that all the manual tasks of providing a label `triage-accepted` can be implemented.
- Implement other actions such that the contributor has the option to sell-assign the issue by typing  `/assign` under the issue comment.

**Describe alternatives you've considered**
There is no alternative that has been considered yet.

**Comment by jLopezbarb** [comment] 2023-04-03 08:45
Hi @NitishKumar06, I'll speak with the team about your proposal. Right now the workflow that we have is:
- User opens an issue
- A member of the team reviews the issue, try to reproduce it and assigns the issue the correct labels
- If someone wants to participate we assign the issue to them. If not we have an internal dashboard by priority where we pull things from it

I would rather continue with the actual workflow because we plan our sprints two weeks ahead, but we don't know who will take care of the issue and if someone from the community wants to work on the issue we need to modify the sprint planning, but I'll speak with the rest of the team to implement the `/assign` command

**Comment by NitishKumar06** [comment] 2023-04-03 09:35
Hi @jLopezbarb , thanks for the response! Please take your time.

**Comment by NitishKumar06** [comment] 2023-06-03 14:58
@jLopezbarb any update or shall we close this issue?

**Comment by jLopezbarb** [comment] 2023-07-24 08:16
Hi @nitishfy, 
Sorry for the late answer. We'd several meeting speaking about the addition of new labels in order to manage the issues better but we've decided that for now we'll continue with the actual system each time a user creates a issue we add the triage label and whenever we do a first insight we categorise the issue. We also spoke about the addition of `/assign` but we wanted to track who is doing which track and with the addition of that label we could potentially lose that.

Hope it helps. If you have any further doubt let us know

**Closed by jLopezbarb** 2023-07-24 08:16 UTC
Labels: triage
