### ISSUE TITLE
In some cases, the okteto deploy command got stuck after the log `forwarding host:`

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#2970] opened 2022-07-28 16:26 UTC
**Describe the bug**
A customer has reported that an `okteto up` execution was stuck deploying the service after seeing the log `forwarding host: ...`.  

After researching the issue, I checking the code between the last log we were seeing and the first missing log and I discovered that in some cases, we are getting some information (branch and commit) regarding git from the local folder https://github.com/okteto/okteto/blob/master/cmd/deploy/deploy.go#L700-L737. So we asked the customer to try the command from a fresh cloned folder and it worked, so it seems that some local git status was provoking the issue.

We have to see if the library we use to get some of the things have some issue reported in this regard or try to reproduce the issue. Maybe the number of local branches in the repo or something similar is the cause

**To Reproduce**
No clear steps to reproduce. The issue was facing when executing a `okteto up` (with a deploy, so the app should not be previously deployed) within a repository folder. An `okteto deploy` should also have the same effect. But we don't know exactly what conditions should satisfy the local copy of the repo

**Expected behavior**
The command should not get stuck. We might try to have a timeout or something and if we don't calculate some of those values, we can keep going with the deployment. That info is not critial to deploy the service

**Desktop (please complete the following information):**
reported with CLI `2.5.0`

**Additional context**
N/A

**Comment by pchico83** [comment] 2022-11-05 11:13
@ifbyol closing it since it's not reproducible

**Comment by AdrianPedriza** [comment] 2023-01-12 15:45
I am able to reproduce similar behavior with our [initial versions](https://github.com/okteto/okteto/tree/adrian/infinite-deploy) of the remote deploy. The remote deploy never finishes. After debugging the issue the code gets stuck here https://github.com/okteto/okteto/blob/adrian/infinite-deploy/cmd/utils/git.go#L79

To reproduce the problem the okteto manifest must have a deploy section prepared for remote deployment. For example:
```yml 
deploy:
  image: okteto/pipeline-runner:1.0.0
  commands:
  - name: deploy nginx
    command: kubectl run nginx --image=nginx
```

**Comment by jLopezbarb** [comment] 2023-01-13 09:07
Reopening since we found a way of reproducing it

**Closed** 2023-05-19 11:45 UTC
Labels: bug, keep, medium, contributor reported, ready
